---
page-layout: full
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
citations-hover: true
format:
  html:
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    page-layout: full
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
---

{{< fa arrow-left >}} back to syllabus

{{< fa file-pdf >}} Print as PDF

{{< fa book >}} Textbook: Haywood & Getchell

+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Module  | Date[^1]                         | Topic[^2]                                                        | Resources                                                                                                                                                                                               | Assignment[^3]                                                                         |
+=========+==================================+==================================================================+=========================================================================================================================================================================================================+========================================================================================+
| 01      | 08/29/22\                        | Course Intro & Syllabus                                          |                                                                                                                                                                                                         | Icebreaker Activity                                                                    |
|         | 08/31/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 02      | 09/05/22 (no class)\             | Chapter 1: Fundamental Concepts                                  | [Slides](https://mycsunemail-my.sharepoint.com/:p:/g/personal/ovande_furtado_csun_edu/ERdJ6u4mr7dEmdZ9qhVJ5nUBpEmuOj_FpIIkhbN768CfIg?e=haLsuZ); [eFlashcards](https://quizlet.com/_1ffi90?x=1jqt&i=dj5) | Quiz CH1; Major Takeaways CH1                                                          |
|         | 09/07/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 03      | 09/12/22 {{< fa video >}}\       | Chapter 2: Theoretical Perspectives                              | [Slides](https://mycsunemail-my.sharepoint.com/:p:/g/personal/ovande_furtado_csun_edu/EacFRMnFUEZMpEuSATg3ua8BxuJgHPc4w8os08iZye4yTQ?e=dgjGiG); [eFlashcards](https://quizlet.com/_1ffi9t?x=1jqt&i=dj5) | Quiz CH2; Major Takeaways CH2                                                          |
|         | 09/14/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 04      | 09/19/22 {{< fa video >}}\       | Chapter 3: Principles of Motion and Stability                    | [Slides](https://mycsunemail-my.sharepoint.com/:p:/g/personal/ovande_furtado_csun_edu/EQzA8HSPvfpKmDe6fLUs_O4By9SVCzwdw5Sz8jtFtDUYTQ?e=85ZdwQ); [eFlashcards](https://quizlet.com/_20zmzf?x=1jqt&i=dj5) | Quiz CH3; Major Takeaways CH3; [Discussion 1 - Dev perspective](assignments/disc1.qmd) |
|         | 09/21/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 05      | 09/26/22 {{< fa video >}}\       | Chapter 4: Early Motor Development                               | [Slides](https://mycsunemail-my.sharepoint.com/:b:/g/personal/ovande_furtado_csun_edu/EQynoMybiC1Ar0v_VARU1fQBzUVFksUlwzY-3P_B9ynzpA?e=4m6wfN); [eFlashcards](https://quizlet.com/_1ffib9?x=1jqt&i=dj5) | Quiz CH4; Major Takeaways CH4                                                          |
|         | 09/28/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 06      | 10/03/22 {{< fa video >}}\       | Chapter 5: Development of Human Locomotion                       | [Slides](https://mycsunemail-my.sharepoint.com/:b:/g/personal/ovande_furtado_csun_edu/EWIwJdLRA-FKpPEOqwTpRPkBcS9efVB6PUsLvCTu0V_7jg?e=1UTeOF); [eFlashcards](https://quizlet.com/_4gw9zz?x=1jqt&i=dj5) | Quiz CH5; Major Takeaways CH5                                                          |
|         | 10/05/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 07[^4]  | 10/10/22 {{< fa video >}}\       | Chapter 6: Development of Ballistic Skills                       | [Slides](https://mycsunemail-my.sharepoint.com/:p:/g/personal/ovande_furtado_csun_edu/EVXypfKAJf1Oq7Df7DtZSyUB35zrMp_BFZIDAWWy65e8gw?e=5NmCTs); [eFlashcards](https://quizlet.com/_c3u3ur?x=1jqt&i=dj5) | Quiz CH6; Major Takeaways CH6; Quiz CH7; Major Takeaways CH7                           |
|         | 10/12/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
|         |                                  | Chapter 7: Development of Manipulative Skills                    | [Slides](https://mycsunemail-my.sharepoint.com/:p:/g/personal/ovande_furtado_csun_edu/EfAWT6Rh5vpOqZWLiSO3VfcBslgDe1brOIDx1QJoWw3b2g?e=YLvSdY); [eFlashcards](https://quizlet.com/_c3u3ur?x=1jqt&i=dj5) |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 08      | 10/17/22 {{< fa user >}}\        | `Labs 1 and 2`                                                   |                                                                                                                                                                                                         |                                                                                        |
|         | 10/19/22 {{< fa user >}}         |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|         | **10/24/22** {{< fa video >}}**\ | `Exam 1`                                                         |                                                                                                                                                                                                         | Study previously covered chapters                                                      |
|         | 10/26/22** {{< fa user >}}       |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 09      | 10/31/22 {{< fa video >}}\       | Chapter 8: Physical Growth, Maturation and Aging                 |                                                                                                                                                                                                         | Quiz CH8; Major Takeaways CH8; [Discussion 2 - Gender](assignments/disc2.qmd)          |
|         | 11/01/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 10      | 11/07/22 {{< fa video >}}\       | Chapter 9: Development and Aging of Body Systems                 |                                                                                                                                                                                                         | Quiz CH9; Major Takeaways CH9                                                          |
|         | 11/09/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
|         |                                  | 5.1 Skeletal System\                                             |                                                                                                                                                                                                         |                                                                                        |
|         |                                  | 5.2 Adipose System\                                              |                                                                                                                                                                                                         |                                                                                        |
|         |                                  | 5.3 Nervous System                                               |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 11      | 11/14/22 {{< fa video >}}\       | Chapter 11: Development of Strength and Flexibility              |                                                                                                                                                                                                         | Quiz CH11; Major Takeaways CH11                                                        |
|         | 11/16/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 12      | 11/21/22 {{< fa video >}}\       | Chapter 12: Weight Status, Fitness, and Motor Competence         |                                                                                                                                                                                                         | Quiz CH12; Major Takeaways CH12; [Discussion 3 - FMS/PA](assignments/disc3.qmd)        |
|         | 11/23/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 13      | 11/28/22 {{< fa video >}}\       | Chapter 15: Social and Cultural Constraints in Motor Development |                                                                                                                                                                                                         | Quiz CH15; Major Takeaways CH15                                                        |
|         | 11/30/22 {{< fa video >}}\       |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| 14      | 12/05/22 {{< fa video >}}\       | Chapter 16: Psychosocial Constraints in Motor Development        |                                                                                                                                                                                                         | Quiz CH16; Major Takeaways CH16                                                        |
|         | 12/07/22 {{< fa video >}}        |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|         | 12/14/22 {{< fa user >}}\        | `Exam 2`                                                         |                                                                                                                                                                                                         | Study previously covered chapters following Exam 1                                     |
|         | 8-10 am                          |                                                                  |                                                                                                                                                                                                         |                                                                                        |
+---------+----------------------------------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+

: Course Sequence {tbl-colwidths="\[10,15,35,15,25\]"}

[^1]: Class Dates: Aug 29, 2022 - Dec 12, 2022

[^2]: Students are expected to read and study the assigned chapters prior to attending each class meeting.

[^3]: Quizzes and Discussions are due Sunday 11:59 pm. (`after` the content is covered). Major takeaways are due on Monday (`before` the content is covered). Refer to the [syllabus](syllabus.qmd) for assignments detailed information.

[^4]: Note that for Module 7 you will be completing activities for both chapters 6 and 7. You will be required to submit separate assignments for each chapter.

{{< fa video >}} Online Meeting via Zoom

{{< fa user >}} In-Person Meeting (RE 278)
