---
title:  'KIN 477: Motor Development'
subtitle: |
  | Department of Kinesiology, Cal State Northridge
  | Syllabus - Fall 2022 (Hybrid)
latex-auto-mk: true
format:
  html:
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    links-as-notes: true
    citations-hover: true
    footnotes-hover: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
table-striped: false
---

# Instructor Info {#sec-instructor-info}

## Brief Bio

Ovande Furtado Jr., Ph.D.

Dr. Furtado received a B.A. in Physical Education from the Federal University of Parana, Curitiba, PR - Brazil. He earned his M.S. and Ph.D. degrees in Motor Behavior from the University of Pittsburgh, PA. Dr. Furtado's line of research focuses on two main areas: (1) validation of observational models in psychomotor assessment instruments and (2) the relationship between motor skill competence, perceived motor competence, physical activity levels, and body composition.

## Office Hours

See @sec-office-hours for more information

## Contact Info

Email: While taking the course ONLY contact me via Canvas Inbox\
Office: Redwood Hall 289

# General Information

## Course Description

Study of age-related changes in motor skills, the processes that underlie these changes, and the factors that influence them.

## Course Prerequisite

KIN 377: Motor Learning (3)

## Course Format

This course consists of readings, written assignments, weekly responses, and check-ins on our Canvas page.

Hybrid (OH) is **a course offering in which students attend class sessions on campus and in an online environment**. The class typically meets approximately half online and half on campus.

::: callout-warning
This course is not self-paced and is not the "softer, easier way"! This means that you have to **1) check in regularly and 2) respond to the weekly assignments.**
:::

## Required Technology Resources {#sec-required-technology-resources}

This course will be taught completely online (no campus meetings will be required), in an asynchronous format (this course will not have scheduled live meeting times). All activities, assignments and exams in this course will be completed via Canvas. To succeed in this course, you must have reliable access to a computer and internet connection. CSUN offers currently enrolled students the option to borrow devices such as computers and internet hotspots through its [Device Loaner Program](https://www.csun.edu/it/device-loaner-program).

## Course Expectations and Goals

Upon completion of this course, you will be able to adequately:

1.  Differentiate developmental topics from other topics (e.g. physical growth, learning, adaptation, maturation). SLO 1, 2, 3 

2.  Analyze current topics pertaining to human movement through a developmental lens. SLO 1, 3 

3.  Apply different theoretical perspectives in explaining developmental change in human motor behavior. SLO 1, 2, 4 

4.  Recognize individual differences in physical growth by comparing and contrasting patterns of growth, and relate these patterns to physiological maturation. SLO 2 

5.  Discuss the developmental periods when rapid change in body systems makes them particularly sensitive to external influences (e.g. deprivation, enrichment). SLO 1 

6.  Synthesize how the body systems interact at various times on the life span continuum. SLO 1 

7.  Use various methodologies and levels of analyses (e.g. product scores, growth measures, developmental sequences, or kinematics) to study motor development. SLO 1, 2

8.  Describe various forms of motor behaviors at various points on the life span and the nature and relation of these behaviors. SLO 1, 4 

9.  Compare and contrast intra- and inter-task developmental sequences of motor skills. SLO 2, 4 

10. Interpret an individual's motor behavior as "more" or "less" advanced on a developmental continuum rather than as "good" or "bad." SLO 4

11. Employ principles of motion and stability to analyze quality of motor skill performance. SLO 1, 2, 3, 4 

12. Compare and contrast movement characteristics of various fundamental or functional movement skills across diverse populations, including various age groups, healthy individuals, and people with disabilities or special needs. SLO 1, 2, 3, 4

## Student Learning Outcomes (SLO'S)

1.  Apply an integrated kinesiological approach to encourage the adoption of healthy and physically active lifestyles, across diverse populations;
2.  Apply evidence-based practices to enhance the study of human movement;
3.  Demonstrate competent problem-solving strategies through intentional practices; and
4.  Demonstrate knowledge of kinesthetic forms, processes, and structures as they apply to the personal expression and culture of human movement.

## Textbook

Haywood, K. M., & Getchell, N. (2019). *Life Span Motor Development* (Seventh edition). Human Kinetics.

ISBN: 9781718210806

Link to Matador Bookstore: <https://bit.ly/3wC1YwG>

## Additional resources

### Access to Computer & Internet

Although not required, it is suggested that you have access to a computer (not simply a tablet and/or smartphone) and Internet throughout this course. Note that CSUN students are eligible to [check out tech devices from CSUN at NO COST](https://www.csun.edu/it/device-loaner-program).

# Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

## Grading Policy

-   **20%**: Weekly Quizzes (12)

-   **20%**: Online Discussions (5)

-   **20%**: Labs (2)

-   **20%**: Exams (2)

-   **20%** Major Takeaways (12)

::: callout-note
One quiz and one discussion with the lowest score will be dropped at the end of the term.
:::

## Grading Scale

A 93.00-100.00 \| A- 90.00-92.99 B+ 87.00-89.99 \| B 83.00-86.99 \| B- 80.00-82.99 C+ 77.00-79.99 \| C 73.00-76.99 \| C- 70.00-72.99 D+ 67.00-69.99 \| D 63.00-66.99 \| D- 60.00-62.99 F \<59.99

::: callout-note
In recognition of the fact that grading, however carefully done, will always be imperfect, this class will utilize a "round up" rule for assigning final grades. I will round up from .5% and above, but anything below this will round down. In other words, 79.5 will round up to 80, while 79.4 will round down to 79 even.
:::

::: callout-important
Requests for an Incomplete (I) must conform to [university policies](https://bit.ly/3bDxwZi). Among other requirements, "I" is possible only for instances in which you are demonstrating passing work in the class.
:::

## Attendance Policy

> *Showing up is 80 percent of life* -- Woody Allen, [via Marshall Brickman](http://quoteinvestigator.com/2013/06/10/showing-up/#note-6553-1)

Although this is an online course, "attendance" is crucial. And by that I mean: **check in Canvas several times a week.**

## E-mail Policy

While taking this course, only communicate with me via `Canvas` \> `Inbox`.

If your message concerns a non-private matter (i.e., assignments, content, deadlines, etc.), then please post your question to the `Q&A Forum` (`Canvas` \> `Discussions` \> `Q&A Forum`), **which can be answered by any student taking the course.**

## Office Hours {#sec-office-hours}

### Online via Microsoft Teams

By appointment only via <http://bit.ly/drfurtado-bookme>

## Make-Up Exam Policy

Unless the student has discussed the situation with the instructor before the assignment's due date and an arrangement has been made, a missed assignment will result in a grade of zero. **Note that making "arrangements" will only be possible given the student provides a valid and written excuse from a reputable source**.

## Late Assignments

Unless you have made previous arrangements, a late assignments will be docked off 5% per day (first 4 days) it is late. All assignments are closed after the 4th day.

## Extra Credit

With the exception of the extra 5 points awarded to the final video performance - LINK (either juggling or cup stacking), there is no individual extra credit granted.

## Disabilities Policy {#sec-disabilities-policy}

Federal law mandates the provision of services at the university-level to qualified students with disabilities.

This instructor, in conjunction with California State University Northridge, is committed to upholding and maintaining all aspects of the federal Americans with Disabilities Act of 1990 (ADA) and Section 504 of the Rehabilitation Act of 1973. If you are a student with a disability and wish to request accommodations, please contact the office of Students with Disabilities Resources located in 110 Student Services Building, or call (818) 677-2684 for an appointment. Any information regarding your disability will remain confidential. Because many accommodations require early planning, requests for accommodations should be made as early as possible. Any requests for accommodations will be reviewed in a timely manner to determine their appropriateness to this setting.

## Academic Dishonesty Policy

*Please, **stop** and read the information below; this is important!*

Each student is expected to be familiar with, and abide by, the conditions of student conduct, as presented in the CSUN Catalog, with emphasis on sections entitled, Student Conduct Code, Academic Dishonesty, Faculty Policy on Academic Dishonesty, and Penalties. Any student engaging in academic dishonesty (e.g., cheating, fabrication, facilitating academic dishonesty, plagiarism) is subject to discipline, which may include a failing grade in the course, and may also be subject to more severe discipline by the University. Students are encouraged to visit the link below and become familiar with the Standards for Student Conduct.

<http://www.csun.edu/a&r/soc/studentconduct.html>

# Course Requirements

To succeed in this course, you will be required to complete several assignments. To avoid surprises, be proactive and review these assignments.

## Quizzes[^1]

[^1]: Due on Sundays 11:59 - after the content is covered

Quizzes will be administered via Canvas and will assess the student's understanding of the topic covered each week. Students are allowed to utilize class notes and the course text to answer the questions; however, **collaboration with other students is not allowed**.

*Here are some other useful information about quizzes:*

1.  When taking quizzes, the questions will appear one at a time and locked after being answered. Thus, students are not allowed to go back and review answers after saving each question.

2.  Correct answers will only be shown to students after the deadline of each quiz.

3.  Refer to `Canvas` and the course sequence for due dates. Please, avoid waiting until the "last minute" to take the quiz. Taking the quizzes earlier will give you enough time to troubleshoot potential technical problems; therefore, plan accordingly.

4.  You will be given a **single** attempt on each quiz. This means you need to study the material before taking each quiz. All quizzes are timed. Students will be given 20 minutes to finish and submit a quiz.

5.  A quiz will only start if the student has a JavaScript-enabled web-browser. Contact [CSUN IT](https://www.csun.edu/it) should you run into technical issues when taking quizzes.

6.  Once opened, a quiz will appear in a full-screen pop-up window that covers all the other windows and has no navigation control

7.  It should be noted that the content of each quiz belongs to [McGraw Hill](https://www.mheducation.com/) (the publisher of our text). Therefore, federal copyright laws prohibit the dissemination of this material. It includes, but is not limited to, posting the quiz online and/or sharing the quiz with someone outside of the classroom.

## Online Discussions[^2]

[^2]: Due on Sundays 11:59 - after the content is covered

You will be required to complete several online discussions while taking this course. The details about each discussion topic will be provided on Canvas. Typically, there are two deadlines for this assignment. First, you need to answer the question I post (deadline 1), then respond to your classmates' posts (deadline 2). Refer to our Class Schedule in Canvas.

## Exams

You will be required to take two exams when taking this course.

## Labs

You will be required to complete two labs by the end of the term.

## Major Takeaways[^3]

[^3]: Due on Mondays before class - before the content is covered

You will be evaluated on your preparedness by submitting an assignment before each class.

# Final (yet important) Notes {#sec-important-notes}

## How to Access our Course and Get Started

-   Log into Canvas: <https://canvas.csun.edu>
-   Under "My Courses," locate our course and click on it.
-   This will take you to the course home page.

## Technology Requirements and Support:

-   A computer and access to the internet (reliable connection)
-   Google Chrome (web browser)
-   A device to record video (phone, tablet, or laptop)

## What I Expect of You:

1.  Online classes are deceiving. Many times new online learners expect them to be easier than face-to-face classes and are surprised to learn how time intensive they are.
2.  Plan your schedule to ensure you have approximately 10 hours per week to spend on this class and take time to identify where and when you'll do your learning.
3.  Review the due dates for the assignments (see Calendar) to orient yourself to the flow of the learning. 4. This course requires regular engagement throughout each week. Plan to reserve a few hours each day to practice the skill you selected for the Learning Task assignment.

## Online Etiquette

All learners in this course will expect to abide by our community ground rules (see below).

Ground Rules: In an effort to ensure our learning community develops, thrives and sustains throughout our time together, the following ground rules will be in effect at all times.

1.  Consider yourself a member of a community. A community is a group of individuals who work together to support a common goal or interest. We are working together to support the successful achievement of our learning outcomes.
2.  Log-in and participate regularly to group conversations and activities.
3.  Treat the diverse contributions made by other community members with respect.
4.  Have patience and a sense of humor with technology.
5.  Be a learner. Keep an open mind when introduced to new ideas that may challenge your perceptions.
6.  Ask for help when you need it, and assist others when possible.
7.  Understand that communications shared through text have a higher likelihood of being misinterpreted than words that are spoken. Therefore, when you type a thought or a comment, read it carefully before you submit it. If you question the way it is worded, read it out loud to yourself. If you still question the way it's phrased, rewrite it.
8.  Contribute regularly to group dialogue, including discussion posts and replies. The contributions of each individual plays a role in the collective strength and diversity of our community.
9.  If, at any time, you feel that any of these ground rules has been violated by a member of our community, you are encouraged to bring your concern directly and immediately to Dr. Furtado. Clearly identify which ground rule has been violated and include specific evidence of the violation in your e-mail or phone call. Your concerns will be addressed promptly and in an individualized manner.

# Accessibility, Academic, and Other Support Resources for Students

## **Disability Resources Available**

The California State University does not discriminate on the basis of disability in admission or access to, or treatment or employment in, its programs and activities. Sections 504 and 508 of the Rehabilitation Act of 1973, the Americans with Disabilities Act of 1990, and various state laws prohibit such discrimination. If you need extra assistance with aspects of this course, please contact the [Disability Resources and Educational Services (DRES)](https://www.csun.edu/dres) or the [National Center on Deafness (NCOD)](https://www.csun.edu/ncod). Reasonable and effective accommodations and services will be provided to students if the requests are made in a timely manner and with appropriate documentation in accordance with federal, state, and university guidelines. Please let me know if you need further information or assistance from me in order to facilitate your learning experience. If you would like to discuss your approved accommodation with me, please let me know and we can set up a virtual appointment. 

## **Additional Campus Resources and Support**

CSUN has a range of resources to support your academic goals, engagement with campus activities and physical and mental health. I encourage you to browse the links below throughout the semester and the rest of your time at CSUN. Please let me know if you would like additional information on any of the resources below. These links are also included on the Canvas site.

## Academic and Technical Resources

-   University [Library](https://library.csun.edu/) for browsing of books, articles, media and additional academic resources.

-   [Learning Resource Center](https://www.csun.edu/undergraduate-studies/learning-resource-center) offers tutoring, a writing center, & more.

-   [Disabilities Resource Educational Services (DRES)](https://www.csun.edu/dres) for assistance with accommodations.

-   [CSUN Information Technology (IT)](https://www.csun.edu/it/need-help) for technology support with Canvas and software related issues. Their office is open for calls/chat M-F from 8am-5pm PST.

-   [CSUN's Accessibility Policy](https://www.csun.edu/universal-design-center/accessibility-statement) for more information on CSUN's goal to ensure that campus communication and information technology is accessible to everyone.

-   [University Library Open Educational Resources (OER)](https://libguides.csun.edu/affordable-learning-solutions/find-affordable-resources/what-are-oer) for affordable Health Science textbooks and educational resources.

## Additional Campus and Community Resources

### **Clubs and Campus Facilities**

-   [Oasis Wellness Center](https://www.csun.edu/oasis) for a welcoming destination where students can find serenity and relaxation, including meditation, massages, and workshops focused on managing stress.

-   [Klotz Student Health Center](https://www.csun.edu/shc) offering medical services, including Telehealth appointments.

-   [Student Recreation Center (SRC)](https://www.csun.edu/src) for exercise and leisure activity that promotes wellness.

-   [Career Center](https://www.csun.edu/career) for career, internship and job resources, resume writing, interview help & more.

-   [USU](https://www.csun.edu/usu) for a variety of services including lactation space, veterans' resources, and more.

-   [Associated Students](https://www.csun.edu/as) providing programs designed to enhance the campus environment.

-   [Financial Aid & Scholarships](https://www.csun.edu/financialaid) offers aid for applications.

### **Additional Resources**

-   [CSUN with A HEART](https://www.csun.edu/heart) for valuable information that will connect you to various resources regarding the basic needs of students in the CSUN campus community.

-   [Food Pantry at CSUN](https://www.csun.edu/mic/csun-food-pantry) providing food and toiletries for CSUN students in need.

-   [University Counseling Center](https://www.csun.edu/counseling) offering free short term counseling services to students, including individual counseling, crisis intervention, group and workshops, and more.

-   [Pride Center](https://www.csun.edu/pride) supporting LGBTQIA+ students through programming and outreach.

-   [Office of Equity and Diversity](https://www.csun.edu/eqd) supporting CSUN's commitment to maintaining an environment where no member of the campus community is subjected to any form of prohibited discrimination in any University program or activity.

-   [Help lines](https://www.csun.edu/helpline) (after hours when the University Counseling is closed) for numerous topics/needs including suicide, drug help, rape or sexual assault, other crisis or urgent concerns and more.

-   [Emergency MataCare grants](https://www.csun.edu/financialaid/matacare-emergency-grant), one-time grants to prevent evictions, urgent childcare issues, etc.

# Class Sequence

{{< include sequence.qmd >}}
