---
title: "Gender Differencers in FMS"
bibliography: ../references.bib
csl: ../apa.csl
---

## Purpose

To...

## Instructions

### Step 1

1.  First, read[^1] [@spessato2013; @haywood2019, chap. 5]

2.  Then answer the following questions:

    1.  what are the potential reasons for the observed differences between boys and girls when performing object-control (OC) and locomotor (LOC) skills?

    2.  what needs to be done to close the gaps?

[^1]: Please, contact the [CSUN University Library](https://library.csun.edu/) to learn you can download @spessato2013 for FREE via the CSU System.

::: callout-important
Ensure to use @spessato2013 and @haywood2019 to back up your answers. Most complete answers will receive the most credit. `Use APA Style in-text citation when answering the questions.`
:::

## Template

::: {.callout-note appearance="minimal" icon="false"}
What are the potential reasons for the observed differences between boys and girls when performing object-control (OC) and locomotor (LOC) skills?

Answer: Phasellus laoreet lorem vel dolor tempus vehicula. Idque Caesaris facere voluntate liceret: sese habere. Ab illo tempore, ab est sed immemorabili. Mercedem aut nummos unde unde extricat, amaras. Praeterea iter est quasdam res quas ex communi. Curabitur blandit tempus ardua ridiculus sed magna. Sed haec quis possit intrepidus aestimare tellus. Quisque ut dolor gravida, placerat libero vel, euismod. Plura mihi bona sunt, inclinet, amari petere vellent.

What needs to be done to close the gaps?

Answer: Curabitur blandit tempus ardua ridiculus sed magna. Sed haec quis possit intrepidus aestimare tellus. Quisque ut dolor gravida, placerat libero vel, euismod. Plura mihi bona sunt, inclinet, amari petere vellent. A communi observantia non est recedendum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus. Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. A communi observantia non est recedendum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus. Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae.
:::

## Submission

Visit our Canvas course, open Discussion 2 under `Discussions`, then:

1.  Make a new post (click Reply)
2.  Copy the Part 2 of the template
3.  Paste the information to the text field in Canvas
4.  Reply to at least 3 classmates' posts by the deadline

### References

::: {#refs}
:::
