---
title: "Do you have a developmental perspective?"
author: Ovande Furtado Jr
citation-location: document
bibliography: ../references.bib
csl: ../apa-numeric-superscript-brackets.csl
format: 
  revealjs:
    incremental: false
    preview-links: false
    controls: true
    menu: false
    footer: "Do you have a developmental perspective?"
    controls-tutorial: true
    link-external-icon: true
    link-citations: false
    link-external-newwindow: true
    progress: true
    footnotes-hover: true
---

# Motivation {.smaller}

To help kinesiology students find out whether they have a developmental perspective when observing individuals while performing motor skills.

> A developmental perspective is essential to our understanding of movement and mobility. A person's motor behavior position at any point in his life reflects his past movement experiences and presages his future ones [@clark2005].

**Click on the right arrow to move to the next slide.**

# Instructions?

You will be presented with 9 questions @woodland2008a. Please, read carefully each question and answer YES or NO. I suggest you to write your answers down.

**Click on the right arrow to move to the next slide.**

# Question 1 {background-color="aquamarine"}

A second grade class is given a running test at the beginning of the school year and again at the end of the year. Most of the children are running faster at the end of the year. Are the children more fit at the end of the year? Are they more skilled runners at the end of the year?

# Question 2 {background-color="aquamarine"}

An eight- year old boy throws a ball for distance keeping his trunk motionless. Is his throwing motion wrong? Should this eight-year-old's physical education teacher or coach show him how to throw correctly?

# Question 3 {background-color="aquamarine"}

Will an 18 year-old college student who has an immature throwing pattern learn to hit a full motion topspin tennis serve in an 8-week class?

# Question 4 {background-color="aquamarine"}

A soccer unit planned for 6th graders is used for 8th graders with very little adjustment. Is this a developmentally appropriate practice?

# Question 5 {background-color="aquamarine"}

Will 4th grade students who can perform soccer dribble, kick, and pass skills during drills be able to able to play a game successfully?

# Question 6 {background-color="aquamarine"}

Some 7th graders in your classes are very good at playing full-court basketball games. Other students are not. To keep the well-skilled students challenged, should you have everyone play a full-court game during part of the class period?

# Question 7 {background-color="aquamarine"}

Will a young child learn to swim more easily than an adult?

# Question 8 {background-color="aquamarine"}

Is it easier to teach an elementary child new skills than it is a teenager?

# Question 9 {background-color="aquamarine"}

Do older adults learn motor skills more slowly than children or younger adults ?

# The Answers

If you answered YES to **ANY** question, you may **NOT** have a "developmental perspective"

# What is the "Developmental Perspective"?

To answer that question let's look at the opening questions again...

# Question 1 - revisited {background-color="blue"}

A second grade class is given a running test at the beginning of the school year and again at the end of the year. Most of the children are running faster at the end of the year. Are the children more fit at the end of the year? Are they more skilled runners at the end of the year?

# Answer to Question 1  {.smaller}

**Development is qualitative**

1)  Development does not just produce changes in quantity but quality as well;
2)  The second graders have matured;
3)  They have longer legs, longer legs run faster;
4)  Their nervous systems coordinate movement better they run faster;
5)  Thus their improvement on the running test may be a result of development;
6)  They may or may not be more fit, but they are certainly are more mature.

# Question 2 - revisited {background-color="blue"}

An eight- year old boy throws a ball for distance keeping his trunk motionless. Is his throwing motion wrong? Should this eight-year-old's physical education teacher or coach show him how to throw correctly?

# Answer to Question 2 {.smaller}

**Developmentally delayed but not wrong**

1)  The throwing pattern is more characteristic of a 3- or 4-year-old. For an 8-year old, this action would be considered developmentally lagging, but it is not wrong.
2)  The physical educator with a developmental perspective is mindful that motor performance of children should not be evaluated using the "adult model" or "error correction model." From the developmental perspective, the boy's teacher should help him develop a mature motor pattern rather than correct an erroneous one.

# Question 3 - revisted {background-color="blue"}

Will an 18 year-old college student who has an immature throwing pattern learn to hit a full motion topspin tennis serve in an 8-week class?

# Answer to Question 3 {.smaller}

**Development is cumulative**

1)  You build on past when developing new skills;
2)  The college student has run into the "proficiency barrier"

-   Cannot become a proficient performer if you fail to develop fundamental skills

3)  The tennis serve is a specialized version of the overhand striking and overhand fundamental motor skills

-   If not proficient in those skills, cannot become proficient in tennis serve

# Question 4 - revisited {background-color="blue"}

A soccer unit planned for 6th graders is used for 8th graders with very little adjustment. Is this a developmentally appropriate practice?

# Answer to Question 4 {.smaller}

**Development is sequential**

1)  This one is obviously inappropriate, but it happens in schools all the time!
2)  Development follows a general pattern
3)  We should build our programs and activities around those sequential changes and build on past experiences from year to year

# Question 5 - revisited {background-color="blue"}

Will 4th grade students who can perform soccer dribble, kick, and pass skills during drills be able to able to play a game successfully?

# Answer to Question 5 {.smaller}

**Development is multifactorial**

1)  Do the fourth graders know the rules
2)  well enough to play?
3)  Are they skillful enough to use their skills in competition? (over learned?)
4)  Are they socially ready for competition?
5)  Many factors weigh in on their readiness for game play

# Question 6 - revisited {background-color="blue"}

Some 7th graders in your classes are very good at playing full-court basketball games. Other students are not. To keep the well-skilled students challenged, should you have everyone play a full-court game during part of the class period?

# Answer to Question 6 {.smaller}

**Development and readiness**

1)  Some are ready for full court games, some aren't
2)  It's inappropriate to expect all students to progress at the same rate
3)  It is inappropriate to expect all students to do the same thing

-   i.e., the same exercises, the same number of exercises, the same distance

4)  Individualize workloads and learning activities
5)  Time is a great way to individualize workload

# Question 7 - revisited {background-color="blue"}

Will a young child learn to swim more easily than an adult?

# Answer to Question 7 {.smaller}

**Development and individual**

A child that is very afraid of the water may find learning to swim much more difficult than an eager, cooperative adult.

# Question 8 - revisted {background-color="blue"}

Is it easier to teach an elementary child new skills than it is a teenager?

# Answer to Question 8 {.smaller}

**Development and readiness**

Although a child is often eager to learn, if the child isn't developmentally ready he/she will not master the new skill.

# Question 9 - revisited {background-color="blue"}

Do older adults learn motor skills more slowly than children or younger adults ?

# Answer to Question 9 {.smaller}

**Development is individual**

Developmental rates are unique to the individual. Mr. Jones, a seasoned citizen of 70, may learn to ride a scooter faster than his 10 year -old nephew. It depends on the individuals involved.

## Development is age-related, not age-dependent

-   Development follows a general pattern (age related)
    -   Each individual has own unique development (not age dependent)
-   Developmental age in typical 3rd grade classroom varies 3 years
-   Average age is 9 but maturity may range from 6 to 12 years
-   Need to teach each child appropriately

## The 6 elements of developmental change {.smaller}

**Development is:**

1.  Individual
2.  Multifactorial
3.  Sequential
4.  Cumulative
5.  Qualitative
6.  Directional (Progresses toward a goal - improvement or adaptation)

## References

{{< refs >}}
