---
title: "Learning Task Update 2"
subtitle: |
           KIN 377 - Motor Learning (Dr. Furtado)
format: 
  html: default
  pdf: default
---

## Purpose

The purpose of this assignment is to assess the students' motor skill learning progression and determine whether they have reached the late associative stage of learning, based on a single performance evaluation.

## Brief Intro

Recall that you have previously completed Updated 1. Now you are being asked to complete the second update for the LT assignment (Update 2).

For this assignment, you must show you are learning the skill you chose to practice (either juggling or cup stacking).

## Where should I start?

1.  Start by carefully studying the content of Appendix A. There, you will learn how to record and submit your video performance for UPDATE 2.

::: callout
Note that these are the same instructions you will follow to turn in your FINAL performance at the end of the semester. The difference is that instead of showing a mastery performance (well into the Fitts & Posner Autonomous stage), for this assignment you are being asked to show progress towards the Associative stage (review Chapter 12 for comparison amongst the three stages as introduced by Fitts & Posner).
:::

2.  Study the summary created by [PSIA-RIA](https://www.psia-rm.org/download/resources/fall_training/PSIA-RM%20&%20Fitts%20&%20Posner%20Stages.pdf) on the Fitts & Posner's Stages of Motor Skill Learning. I will use a [rubric](377-appendix-d.qmd) based on their document to assess your performance.
3.  Practice the skill you selected for the Learning Task Assignment (juggling OR cup stacking) throughout this week until you can perform (at least) at the level of the LATE ASSOCIATIVE stage.
4.  Video-record yourself (or ask someone to record you) performing the skill 3 times - Refer to [Appendix A](https://drfurtado.github.io/site/courses/377/syllabus.html#video-recording-for-juggling-or-cup-stacking "Link") for instructions.
5.  Submit the video for grading through [Canvas](http://canvas.csun.edu).

::: callout
Review the checklist below before submitting this assignment.
:::

**Checklist - Juggling**

1.  I have followed the steps above prior to submitting my video
2.  I have submitted a single video containing 3 attempts
3.  I have not stopped **the video** in between attempts
4.  I waited 2-3 seconds in between attempts
5.  I did not edit the post-recorded video in any shape or form
6.  I performed following the guidelines from Appendix A and am aware of the ONLY [technique that will be accepted](https://youtu.be/yAcDYYvXTaA?t=3)
7.  I did NOT submit a video that depicts me performing [juggling with pause](https://youtu.be/whiwiYz20Fo) or [juggling in circling motion](https://youtu.be/sFSHpxQQchQ)  
8.  I understand that if I submit a video that depicts me performing with only 1 or 2 objects, the video will be returned and the late policy may apply
9.  I understand that if I submit a video that depicts me performing with plastic bags or scarves, the video will be returned and the late policy may apply
10. Failing to comply with items 5-9, will result in the video being returned to the student and the resubmission will be subjected to the "late submission" policy outlined in our syllabus.

**Checklist - Cup Stacking**

1.  have followed the steps above prior to submitting my video
2.  I have submitted a single video containing 3 attempts
3.  I have not stopped **the video** in between attempts
4.  I waited 2-3 seconds in between attempts
5.  I did not edit the post-recorded video in any shape or form
6.  I performed following the guidelines from Appendix A and am aware of the ONLY [technique that will be accepted](https://youtu.be/slf2ZNCYmGk)
7.  I use **both hands** to upstack/downstack during all steps - [contrary to this example](https://youtu.be/9LxYIE7b-bI)
8.  I use professional or semi-professional cups instead of [ordinal plastic cups](https://youtu.be/UrBMRXqfLus)
9.  Once done upstacking on one side (left or right), I go back to the other side to begin the downstack
