---
page-layout: full
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
citations-hover: true
link-external-icon: true
link-external-newwindow: true
links-as-notes: true
table-striped: true
table-hover: true
tbl-colwidths: [10,10,55,25]
---

Textbook: Magill and Anderson @magill2020b

+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| Module   | Week of  | Topic                                                   | Assignments                                                                                     |
+==========+==========+=========================================================+=================================================================================================+
| **1**    |          |                                                         | Discussion 1                                                                                    |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **2**    |          |                                                         | Quiz Ch01                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **3**    |          |                                                         | Quiz Ch11                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|          |          |                                                         | Quiz Ch12                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **4**    |          |                                                         | Quiz Ch12                                                                                       |
|          |          |                                                         |                                                                                                 |
|          |          |                                                         | Quiz Ch11                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **5**    | 02/27/23 | `Learning Task - Update 1`                              | Complete requirements and submit assignment by the due date                                     |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **6**    | 03/06/23 | Ch14: Demonstration and verbal instructions             | Quiz Ch14, Discussion Ch14                                                                      |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **7**    | 03/13/23 | Ch15: Augmented feedback                                | Quiz Ch15                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|          | 03/20/23 | `Spring recess`                                         | na                                                                                              |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **8**    | 03/27/23 | Ch16: Practice variability                              | Quiz Ch16                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **9**    | 04/03/23 | Ch17: The amount & distribution of practice             | Quiz Ch17, Discussion Ch17                                                                      |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **10**   | 04/10/23 | `Learning Task - Update 2`                              | Complete requirements and submit assignment by the due date                                     |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **11**   | 04/17/23 | Ch18: Whole and part-practice                           | Quiz Ch18                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **12**   | 04/24/23 | Ch09: Attention                                         | Quiz Ch09, Discussion 4                                                                         |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **13**   | 05/01/23 | Ch13: Transfer of learning                              | Quiz Ch13                                                                                       |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **14**   | 05/08/23 | `Learning Task - Update 3`                              | Complete requirements and submit assignment by the due date                                     |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| **15**   | 05/15/23 | → finish and submit the reflection paper\               | Complete requirements and submit assignments by the due date                                    |
|          |          | → record and submit the performance video\              |                                                                                                 |
|          |          | `Refer to Appendices A, B, C`                           |                                                                                                 |
+----------+----------+---------------------------------------------------------+-------------------------------------------------------------------------------------------------+

: Course Sequence

::: {#refs}
:::
