Magill, R. A., & Anderson, D. (2020). Motor learning and control: concepts and applications (12th Ed.). McGraw-Hill Education.

Link to Matador Bookstore: <https://bit.ly/37yiD7u>

::: callout-note
The program below is only available during the Fall and Spring semesters.
:::

### myCSUNDigitalAccess Program {#sec-mycsundigitalaccess}

1.  You are enrolled in a course which is part of the myCSUNDigitalAccess (MCDA) program.
2.  The *MCDA* program provides digital materials to students at a deeply discounted price.
3.  Some or all of your materials for this course are being provided digitally through the *MCDA* program.
4.  ALL enrolled students will have access to the materials through Canvas by the 1st day of class, *but more likely earlier*.
5.  If you want to keep access throughout the semester, you need do nothing. A charge will be placed on your CSUN student portal account (just like tuition, but a separate charge) around the 5th or 6th week of classes. You will then be responsible for paying the university.
6.  If you choose to obtain your materials elsewhere you have until **`02/17/23`** to Opt-Out (see instructions below). Those who Opt-Out by **`02/17/23`** will lose access and will **not be charged**.
7.  Anyone who does not Opt-Out by the **`02/17/23`** deadline will be charged and those charges **will not be reversible**.
8.  [Click here for more information](https://bit.ly/3pcWcfb).

### Price

To see how much you will be billed if you opt-in, click the link below:

<https://bit.ly/3PDiGCx>

### Opt-out Instructions

If you wish to opt out of this program and not purchase access to the required digital materials you will need to follow the steps below by **`02/17/23`**:

1.  Go to <https://accessportal.follett.com/0150>
2.  Click on Create an Account on the lower right
3.  Create an account using your CSUN email account
4.  Select the course(s) you wish to Opt-Out from

::: callout-note
You will receive an email confirming your Opt Out selection, access will be removed and you will need to purchase the materials elsewhere on your own. For more information about this program, please visit the following link: <https://bit.ly/3pcWcfb>
:::

