---
page-layout: full
bibliography: references.bib
citations-hover: true
link-external-icon: false
link-external-newwindow: true
links-as-notes: true
tbl-colwidths: [10,10,50,30]
identifier-prefix: sch
csl: ../apa.csl
---

Required textbook: @magill2020

[Lectures notes in PDF](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv)

{{< bi laptop >}} : Online via Zoom {{< bi person >}} : On Campus

::: callout-important
I suggest you to read and study the assigned content (chapters, videos, eFlashcards, etc.) first, then watch the video/audio lectures.
:::

::: callout-warning
I teach three different sections of KIN 377, one hybrid and two fully online. Even though it shows in Canvas you are in section #19392, you still belong to the section you originally enrolled. To find out, log into the CSUN Portal and verify your original enrollment.

So, if the CSUN Portal says you are in 

-   **KIN 377 MOTOR LEARNING - (19430-SP2023); or**

-   **KIN 377 MOTOR LEARNING - (19780-SP2023)**

**Then, THERE ARE NO ON-CAMPUS OR ONLINE MEETINGS. You are enrolled in a FULLY online (asynchronous) course.**

And if the CSUN Portal says you are in

-   **KIN 377 MOTOR LEARNING - (19392-SP2023)**

**Then, there will be online and on-campus meetings.**
:::

+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| Mode[^1]          | Week of      | Study Content[^2]                                                                                                                                                                   | Assignments                   |
+===================+==============+=====================================================================================================================================================================================+===============================+
| {{< bi laptop >}} | 01/23/23     | Intro to Course & Survival Skills\                                                                                                                                                  | Read and study the Syllabus   |
|                   |              | [APA Style Article](https://drfurtado.github.io/site/blog/posts/apa-citation-basics/)                                                                                               |                               |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 01/30/23     | [Ch01](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): The classification of motor skills\   | Quiz                          |
|                   |              | [How to learn anything](https://youtu.be/5MgBikgcWnY)\                                                                                                                              |                               |
|                   |              | [eFlashcards](https://quizlet.com/_zs84k?x=1jqt&i=dj5)\                                                                                                                             |                               |
|                   |              | Video/Audio Lecture (link coming soon)[^3]                                                                                                                                          |                               |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi person >}} | 02/06/23     | [Ch11](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Defining and assessing learning       | Quiz; Discussion              |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 02/13/23     | [Ch12](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): The stages of learning                | Quiz                          |
|                   |              |                                                                                                                                                                                     |                               |
|                   |              | [In-class Activity](https://mycsunemail-my.sharepoint.com/:w:/g/personal/ovande_furtado_csun_edu/EeT9iGnQVtZNhHxSsvjuLpAB7Pb3h4avxAw6-WE2YYAVjA?e=bezgXP)                           |                               |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 02/20/23     | `Learning Task - Update 1`                                                                                                                                                          | Finish and submit assignment  |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 02/27/23     | [Ch14](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Demonstration and verbal instructions | Quiz; Discussion              |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi person >}} | 03/06/23     | [Ch15](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Augmented feedback                    | Quiz                          |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 03/13/23     | [Ch16](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Practice variability                  | Quiz                          |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| na                | 03/20/23     | `Spring recess`                                                                                                                                                                     | na                            |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 03/27/23     | [Ch17](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): The amount & distribution of practice | Quiz; Discussion              |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 04/03/23     | `Learning Task - Update 2`                                                                                                                                                          | Finish and submit assignment  |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 04/10/23     | [Ch18](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Whole and part-practice               | Quiz                          |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 04/17/23     | [Ch09](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Attention                             | Quiz; Discussion              |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi person >}} | 04/24/23     | [Ch13](https://mycsunemail-my.sharepoint.com/:f:/g/personal/ovande_furtado_csun_edu/Ev6ETvvCJWBKjDvloNKf4eUBh_daD-cgTZsITXFjmVaJwA?e=xEtHUv): Transfer of learning                  | Quiz                          |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 05/01/23     | `Learning Task - Update 3`                                                                                                                                                          | Finish and submit assignment  |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi person >}} | 05/08/23     | Special Topic                                                                                                                                                                       |                               |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+
| {{< bi laptop >}} | 05/15/23\    | Finish and submit the reflection paper\                                                                                                                                             | Finish and submit assignments |
|                   | Final's Week | Record and submit the performance video\                                                                                                                                            |                               |
|                   |              | `Refer to Appendices A, B, C`                                                                                                                                                       |                               |
+-------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+

[^1]: Only applies to Hybrid sections. Fully Online (OF) sections do not meet online or on campus.

[^2]: In addition to the main reading [@magill2020], students are responsible for other materials assigned each week. This may include videos, articles, and eFlahscards.

[^3]: Typically posted on Wednesday of each week. This gives you time to read and study the content (assigned chapter, videos, etc.) before going over the video/audio lecture.
