---
title: "KIN 377 - LT Update 3"
author: "Dr. Furtado"
date: today
format: compact-pdf
---

# Requirements

-   Read the content of Appendix C (<https://bit.ly/3VlYidC>)

# Instructions

This is the last update before you submit your video performance at the end of the semester. You will be required to do the following:

1.  Pick TWO of the principles (refer to Appendix C) you have been using to learn your selected motor skill (juggling or speed cut stacking).

2.  For EACH, provide the following:

    1.  The principle's name and definition (make sure to cite our textbook properly)

    2.  A description of how the principle is helping you to progress through the Fitts & Posner Stages of Learning (BE SPECIFIC)

    3.  The hurdles you have faced when trying to employ the principle as a learning strategy (BE SPECIFIC)

# Submission

This assignment is similar to a Discussion.

**Notes**

-   1st response: by THURSDAY 11:59 pm (response to my post).

-   2nd response: by SUNDAY 11:59 pm (responses to 3 posts submitted by your classmates)

-   Length of 1s response: \~350 words; 2nd response \~150 words each response (total of 3)

-   Users must post before seeing replies You will be required to cite our textbook as part of your response. THIS MEANS YOU MUST ADD IN-TEXT CITATIONS (NOT SIMPLY PROVIDE THE SOURCE) AS PART OF YOUR WRITE-UP. REFER TO THE CONTENT OF WEEK 1 RELATED TO IN-TEXT CITATIONS.

-   I encourage you to type in your answer to my question above elsewhere (e.g., Word document), then copy the content, and...PLEASE, DO NOT ATTACH ANY FILES FOR THIS ASSIGNMENT. INSTEAD, COPY AND PASTE YOUR ANSWERS TO THE CANVAS TEXT BOX.

**Resources**

-   [Click here](https://drfurtado.github.io/site/courses/377/syllabus.html#appendix-d) to learn how to access the Evaluation Rubric for this assignment.

-   [Click here](https://mycsunemail-my.sharepoint.com/:w:/g/personal/ovande_furtado_csun_edu/EYxJHESvsAhEg-MXzmlY70EBeM9XdBO5hXo561QS7jNqEw?e=VGXanv) to download a template.

# Grading rubric

[Click here](https://drfurtado.github.io/site/courses/377/rubric-update3.html) to open rubric for this assignment
