---
title: "Lesson 8: Correlation & Bivariate Regression"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## What is Correlation?

Correlation is used to quantify the degree of relationship, or association, between variables.​

Here are some examples:

-   Correlation between vertical jump and power clean​

-   Correlation between skinfold thickness and percentage of body fat​

The Pearson product moment correlation coefficient (Pearson r)​ is named after Karl Pearson and the $r$ values range from −1.00 to +1.00.​ The closer r is to │1.0│, the stronger the relationship.​ If r = 0.0, then there is no relationship between the variables.​

Correlation is the extent to which the direction and size of deviations from the mean in one variable are related to the direction and size of deviations from the mean in another variable. A positive correlation occurs when participants who score above the mean on Variable A and Variable B Y, and vice versa (e.g., power clean and vertical jump)​

Negative correlation: subjects who score below mean on X score above mean on Y, and vice versa (vertical jump and 40-yard dash time) ​

Z scores: positive if above the mean, negative if below the mean ​

Magnitude: look at absolute value of r​

Direction: look at sign of r​
