---
title: "KIN 610 - Course Sequence"
link-external-newwindow: true
page-layout: full
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
citations-hover: true
link-external-icon: true
link-external-newwindow: true
links-as-notes: true
---

Textbook: Weir and Vincent (2021) @weir2021

+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| Lesson                | Date[^1] | Reading[^2]                                         | Assignments[^3]                                       |
+=======================+==========+=====================================================+=======================================================+
| [Lesson01](les01.qmd) | 08/29/22 | Ch01: Measurement, Statistics, and Research         | Quiz 1; Major Takeaways                               |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson02](les02.qmd) | 09/05/22 | Ch02: Organizing and Displaying Data\               | Quiz 2; Major Takeaways                               |
|                       |          | Ch03: Percentiles                                   |                                                       |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson03](les03.qmd) | 09/12/22 | Ch04: Measures of Central Tendency\                 | Quiz 3; Major Takeaways                               |
|                       |          | Ch05: Measures of Variability                       |                                                       |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson04](les04.qmd) | 09/19/22 | Ch06: The Normal Curve\                             | Quiz 4; Major Takeaways; [Homework 1](assig/hw01.qmd) |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson05](les05.qmd) | 09/26/22 | Ch07: Fundamentals of Statistical Inference         | Quiz 5; Major Takeaways                               |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson06](les06.qmd) | 10/03/22 | Ch08: Correlation and Bivariate Regression          | Quiz 6; Major Takeaways                               |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson07](les07.qmd) | 10/10/22 | Ch09: Multiple Correlation and Multiple Regression\ | Quiz 7; Major Takeaways; Homework 2                   |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| na                    | 10/17/22 | `Exam 1`                                            | na                                                    |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson08](les08.qmd) | 10/24/22 | Ch10: The Student's *t*-test\                       | Quiz 8; Major Takeaways                               |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson09](les09.qmd) | 10/31/22 | Ch11: Simple Analysis of Variance\                  | Quiz 9; Major Takeaways                               |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson10](les10.qmd) | 11/07/22 | Ch12: Analysis of Variance With Repeated Measures\  | Quiz 10; Major Takeaways; Homework 3                  |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson11](les11.qmd) | 11/14/22 | Ch13: Quantifying Reliability\                      | Quiz 11; Major Takeaways                              |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson12](les12.qmd) | 11/21/22 | Ch14: Factorial Analysis of Variance\               | Quiz 12; Major Takeaways                              |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson13](les13.qmd) | 11/28/22 | Ch15: Analysis of Covariance\                       | Quiz 13; Major Takeaways                              |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| [Lesson14](les14.qmd) | 12/05/22 | Ch16: Analysis of Nonparametric Data\               | Quiz 14; Major Takeaways                              |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+
| na                    | 12/13/22 | `Exam 2`                                            | na                                                    |
+-----------------------+----------+-----------------------------------------------------+-------------------------------------------------------+

: Course Calendar {tbl-colwidths="\[15,15,40,20\]"}

[^1]: Class Dates: Aug 29, 2022 - Dec 12, 2022

[^2]: Students are expected to read and study the assigned chapters prior to attending each class meeting.

[^3]: Unless stated otherwise, all assignments are due before class. Refer to the [syllabus](syllabus.qmd) for assignments detailed information.
