---
title:  'KIN 610: Quantitative Analysis of Research in Kinesiology'
subtitle: |
  | Department of Kinesiology, Cal State Northridge
  | Fall 2022 | Tuesday, 4:00-6:45 p.m (RE 276)
latex-auto-mk: true
format: 
  html:
    toc: true
    toc-location: right
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    links-as-notes: true
    citations-hover: true
    footnotes-hover: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
bibliography: references.bib
csl: apa-numeric-superscript-brackets.csl
---

# Instructor Info {#sec-instructor-info}

**Brief Bio**

Ovande Furtado Jr., Ph.D.

Dr. Furtado received a B.A. in Physical Education from the Federal University of Parana, Curitiba, PR - Brazil. He earned his M.S. and Ph.D. degrees in Motor Behavior from the University of Pittsburgh, PA. Dr. Furtado's line of research focuses on two main areas: (1) validation of observational models in psychomotor assessment instruments and (2) the relationship between motor skill competence, perceived motor competence, physical activity levels, and body composition.

**Office Hours**

See @sec-office-hours for more information

**Contact Info**

Email: ovandef\@csun.edu\
Office: Redwood Hall 289

## Course Description {#sec-course-description}

This course focuses on the introductory statistical techniques used in social science research. Students will be introduced to concepts such as reliability, validity, measures of central tendency, variability, probability, and statistical techniques including: t tests (independent & dependent samples), Analysis of Variance (ANOVA), Chi-square, correlation, and regression.

Students are expected to take the material/concepts presented in this course and apply them through a series of homework assignments and quizzes. The overall goal of the course is not only to help students understand the mathematical/statistical concepts presented but also to assist in the application of these procedures.

::: callout-note
I reserve the right to make changes to this syllabus at any point in the semester. I will inform you in class and via email and an updated syllabus will be posted on Canvas.
:::

## Expectations and Goals

Upon completion of this course, you will be able to adequately:

1.  Introduce statistical concepts utilized in research within the social sciences

2.  Apply the mathematical/statistical techniques presented for social science research

3.  Demonstrate an ability to analyze and interpret data within the social sciences

4.  Provide practical examples as to when statistical techniques presented are appropriate methods for analysis.

## Text, readings & instructional resources

### Textbook (required)

Weir and Vincent (2021) @weir2021

### Other readings

-   StatKat - Statistical method selection table

-   GPower - Statistical Power Analysis

    -   HHU website[@universi2014] (many resources related to the app, including tutorials)

    -   Demonstration Article[@faul2007]

### Instructional resources {#instructional-resources}

-   jamovi Statistical Software[@thejamoviproject2021] (Free)

-   jamovi Video Tutorials[^1] (Free)

[^1]: [jamovi video tutorials](https://bit.ly/2VHvd1w)

## Structure & Requirements {#sec-structure-requirements}

You are responsible for the material covered in the textbook prior to attending each class. Note that the week's readings are specified in the [course sequence](sequence.qmd).

In addition to these readings, the instructor may assign supplemental readings throughout the semester. These supplemental readings do not appear on the schedule as these readings will be assigned at the instructor's discretion.

The assignments used to enhance your learning experience in this course include:

### Preparedness

You will be evaluated on your preparedness by submitting an assignment before each class ([Major Takeaways](assig/mt00.qmd)).

### Participation & Attendance {#sec-participation-attendance}

Class presence and participation points are given to encourage your active class participation and discussion. You will be rewarded with a perfect score **as long as you frequently come to class and actively contribute to the class discussion during lectures**.

Although it is not required, most students send their professor a brief e-mail to explain their absence in advance.

### Quizzes {#sec-quizzes}

**Before each class**, you will complete a multiple-choice quiz on the topic covered for that week. You will be given multiples attempts and the highest grade will be used.

### Homeworks {#homeworks}

Students will complete three (3) homework assignments on this course. The purpose of each assignment is to assist students in applying their understanding of the statistical procedures discussed in class as well as to provide an opportunity for students to respond to the readings.

Homework assignments have two components. The first part is performing the statistical calculations correctly using jamovi. The second component involves interpreting the statistical analyses. When answering the interpretation questions, the point is to show that you know what your numbers mean, so don't simply provide the definition of the term. For instance, if you calculate the "number needed to treat (NNT)" as NNT = 7.69, the interpretation of this number is something like "7.69 people must be given the treatment to prevent one adverse event. The wrong answer is something like"the NNT tells you how many people must be given the treatment to prevent one adverse event."

::: callout-warning
You are allowed to discuss homework with other students (and with the instructor), but you must write final answers yourself, in your own words. Solutions prepared "in committee" or by copying or paraphrasing someone else's work are not acceptable; your hand-in assignments must represent your own thoughts (refer to \[Academic Dishonesty Policy\](#dishonesty) for more information); especially, the information about PLAGIARISM.
:::

### Exams

You will be required to complete two (2) exams in this course. Students may use their notes and textbook for the exams, but no other outside resource other than a calculator can be used.

Each exam have 10 questions, with each question worth 10 points. Exams must be completed in the allotted time. The focus of the exams (and quizzes) will be on concepts and interpretation, with most of the computational activities occurring in the homework assignments.

Although the quizzes and exams will not focus on previously tested material (they are not meant to be cumulative), knowledge of previously tested material may be inherently required to answer questions related to new material.

Most of the computational activities will be via the homework assignments. In addition, selected readings will be assigned through the semester. The content of these readings will be included on exam and quiz questions and in homework assignments.

## Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

### Grading

| Assignment                 | Percentage |
|----------------------------|------------|
| Major Takeaways (14)\*     | 15%        |
| Participation & Attendance | 5%         |
| Weekly Quizzes (14)\*      | 20%        |
| Homeworks (3)              | 30%        |
| Exams (2)                  | 30%        |

\*The lowest score will be dropped at the end of the semester.

### Grading Scale

A 93.00-100.00 \| A- 90.00-92.99 B+ 87.00-89.99 \| B 83.00-86.99 \| B- 80.00-82.99 C+ 77.00-79.99 \| C 73.00-76.99 \| C- 70.00-72.99 D+ 67.00-69.99 \| D 63.00-66.99 \| D- 60.00-62.99 F \<59.99

::: callout-note
In recognition of the fact that grading, however carefully done, will always be imperfect, this class will utilize a "round up" rule for assigning final grades. I will round up from .5% and above, but anything below this will round down. In other words, 79.5 will round up to 80, while 79.4 will round down to 79 even.
:::

::: callout-important
Requests for an Incomplete (I) must conform to [university policies](https://bit.ly/3bDxwZi). Among other requirements, "I" is possible only for instances in which you are demonstrating passing work in the class.
:::

### Attendance

> *Showing up is 80 percent of life* -- Woody Allen, [via Marshall Brickman](http://quoteinvestigator.com/2013/06/10/showing-up/#note-6553-1)

Attendance will be taken at the beginning of every class; please, plan accordingly.

### E-mail

While taking this course, only communicate with me via `Canvas` \> `Inbox`.

If your message concerns a non-private matter (i.e., assignments, content, deadlines, etc.), then please post your question to the `Q&A Forum` (`Canvas` \> `Discussions` \> `Q&A Forum`), **which can be answered by any student taking the course.**

### Office Hours {#sec-office-hours}

#### In-person

Tuesdays from 9-11 am at RE 289.

#### Online via Zoom

By appointment only via <https://calendly.com/drfurtado>

### Late Assignments {#sec-late-assignments}

Unless you have made previous arrangements, a late assignments will be docked 10% per day (first 4 days) it is late. Students will not be allowed to submit assignments after the fourth day of the deadline.

### Extra Credit

There is no individual extra credit granted. Therefore, do not plan to make-up poor grades at the end of the semester by asking to do extra credit work. I might provide extra credit opportunities, but these will be offered to the entire class, not to individuals.

### Disabilities {#sec-disabilities}

Federal law mandates the provision of services at the university-level to qualified students with disabilities.

This instructor, in conjunction with California State University Northridge, is committed to upholding and maintaining all aspects of the federal Americans with Disabilities Act of 1990 (ADA) and Section 504 of the Rehabilitation Act of 1973.

If you are a student with a disability and wish to request accommodations, please contact the office of Students with Disabilities Resources located in 110 Student Services Building, or call (818) 677-2684 for an appointment. Any information regarding your disability will remain confidential. Because many accommodations require early planning, requests for accommodations should be made as early as possible. Any requests for accommodations will be reviewed in a timely manner to determine their appropriateness to this setting.

### Academic Dishonesty {#dishonesty}

*Please, **stop** and read the information below; this is important!*

::: callout-important
Each student is expected to be familiar with, and abide by, the conditions of student conduct, as presented in the CSUN Catalog, with emphasis on sections entitled, Student Conduct Code, Academic Dishonesty, Faculty Policy on Academic Dishonesty, and Penalties. Any student engaging in academic dishonesty (e.g., cheating, fabrication, facilitating academic dishonesty, plagiarism) is subject to discipline, which may include a failing grade in the course, and may also be subject to more severe discipline by the University. Students are encouraged to visit the link below and become familiar with the Standards for Student Conduct.

<http://www.csun.edu/a&r/soc/studentconduct.html>
:::

#### About Plagiarism

Plagiarism means using words, ideas, or arguments from another person or source without citation[^2]. Cite all sources consulted to any extent (including material from the internet), whether or not assigned and whether or not quoted directly. For quotations, four or more words used in sequence must be set off in quotation marks, with the source identified.

[^2]: Except for Homeworks. your hand-in assignments must represent your own thoughts (refer to [Academic Dishonesty Policy](#dishonesty) for more information); especially, the information about PLAGIARISM.

Plagiarism is a serious violation of the CSUN Student Conduct Code. Please read my comment about plagiarism under [Homeworks](#homeworks). Any form of cheating will immediately earn you a failing grade for the entire course. **By remaining enrolled, you consent to this policy**.

> Turnitin (see below) will detect such misconducts as it checks every submission against a database of papers, as well as against the Internet.

What is Turnitin?

[Turnitin](https://www.turnitin.com/) is an automated system that instructors can use to quickly and easily compare each student's assignment with billions of websites, as well as an enormous database of student papers that grows with each submission. Accordingly, you will be expected to submit assignments through the Canvas Assignment Tool in electronic format. After the assignment is processed, as an instructor, I receive a report from *Turnitin* that states if and how another author's work was used in the assignment.

## Final (yet important) Notes {#sec-final-notes}

### How to Access our Course and Get Started

-   Log into Canvas: <https://canvas.csun.edu>
-   Under "My Courses," locate our course and click on it.
-   This will take you to the course home page.

### Technology Requirements and Support:

-   A computer and access to the internet (reliable connection)
-   Google Chrome (web browser)

### What I Expect of You:

1.  Plan your schedule to ensure you several hours per week to spend on this class and take time to identify where and when you'll do your learning.
2.  Review the due dates for the assignments (refer to our Course Schedule in Canvas) to orient yourself to the flow of the learning.
3.  This course requires regular engagement and practice using [jamovi](#instructional-resources) (Statistical Package).

## How to be Success in this Course {#sec-success}

Consider the goals you have for engaging in this course as you determine how to allocate time to complete course requirements.

Each student has a different pace when comes to studying for a course. Thus, I will let you figure out how many hours you need to reserve each week for this course. Regardless of the number of hours chosen, try to divide your time so that you devote more time to `assignments` and `assigned readings`.

The Module Time chart below provides a visual representation of the typical time spent completing a module, followed by an example weekly schedule.

### Module time

A typical module in this course is comprised of the following categories:

1.  Readings + eFlashcards
2.  Mini-lecture
3.  Practice `jamovi`
4.  Assignments (major takeaways, quizzes)

```{r echo=FALSE}
# Pie Chart with Percentages
slices <- c(30, 15, 15, 40)
lbls <- c("Assignments", "Mini-lectures", "Practice jamovi", "Readings+eFlashcards")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels
pie(slices,labels = lbls, main="Module Time") 

```

### Example Weekly Schedule

-   Monday-Tuesday (or get a jump-start on the weekend)
    -   Read the chapter(s) + Study the eFlashcards
-   Wednesday-Thursday
    -   Watch the mini-lectures + Practice jamovi
-   Friday-Sunday
    -   Complete the assignments

## Student Support Services {#sec-student-support-services}

CSUN aims to make all learning experiences as accessible as possible, and has a variety of resources available to help support students. If you believe the design of this course poses barriers to effectively participate or demonstrate your learning, please contact me to discuss possible options and adjustments.

-   The IT Help Center (818)677-1400, helpcenter\@csun.edu is available to help with Canvas, CSUN e-mail, SOLAR/Portal, and other technical issues.
-   CSUN Device Loaner Program (<https://bit.ly/3t1G0An>) provides devices that can be checked out that includes laptops, webcams, hotspots and headsets
-   The Learning Resource Center (818) 677-2033 The mission of the LRC is to enable students to improve their academic performance through a variety of learning programs, including workshops, one-on-one and group tutoring, supplemental instruction classes and interactive subject area computer programs and videos. Student who use the LRC learning programs will develop and strengthen their critical thinking skills, study strategies, writing skills and performance in subject matter courses.
-   University Counseling Services (818) 677-2366, Bayramian Hall 520. UCS provides resources and information to assist students in dealing with a variety of large and small psychological obstacles that may interfere with academic progress and/or relationship satisfaction. Services include individual, group, and crisis counseling.
-   In accordance with the CSUN Accessibility Policy (<https://bit.ly/3yqGHE9>), CSUN is working to ensure that campus communication and course materials are accessible to everyone. Please reach out to me if you have difficulty with any of the materials for this course.
-   If you have a disability and need accommodations, please register with the Disability Resources and Educational Services (DRES) office or the National Center on Deafness (NCOD).
    -   The DRES office can be reached at (818) 677-2684.
    -   NCOD can be reached at (818) 677-2611.
    -   Reasonable accommodations and services will be provided to students if requests are made in a timely manner and with appropriate documentation
    -   If you would like to discuss your need for accommodations with me, please drop in office hours or contact me to set up an appointment.
-   Food Pantry (<https://bit.ly/38nTsVH>) at CSUN: Anybody who faces challenges securing food or housing and believes this impacts course performance, should contact CSUN's Food Pantry website and the corresponding contacts. If you also feel comfortable contacting me, the department chair, or the Dean's Office, we can also facilitate assistance. You don't have to be alone in this moment.
-   Emergency MataCare grants (<https://bit.ly/2WAZkIz>), one-time grants to prevent evictions, urgent child care issues, etc. - DACA (Deferred Action for Childhood Arrivals) Resources: Check out the Central American Resource Center facebook page (https://bit.ly/2Yg0p9z), legal resources listed on CSUN's Educational Opportunity Program (EOP) Dream Center that was created to support all undocumented students & allies (Dream Center flyer). CSUN President Harrison issued a support statement on the CSUN homepage for DACA and resources.
-   Help lines (https://bit.ly/3sYbMOo)(after hours when the University Counseling is closed) for numerous topics/needs (e.g., suicide, drug, rape, LGBQT, military, or any crisis). You don't have to manage these feelings alone.
-   Pride Center (https://bit.ly/3jqNZUi) offers support and resources to lesbian, gay, bisexual, transgender, queer, & questioning students, faculty, & staff.
-   Klotz Student Health Center (https://bit.ly/3zx1Y0s): Numerous health services including primary care, dental, nutritional counseling, acupuncture, massage and lots more.
-   Career Center (https://bit.ly/3jtTcL2) for resume writing & interviewing and much more; Matty's Closet (https://bit.ly/3jAResx) has free professional clothes for students who need interview or professional attire.
-   USU 9https://bit.ly/38uz59j) for more student services; Clubs & Organizations (https://bit.ly/38tBhOa): Hopefully a dozen people have already advised you to "get involved" (https://bit.ly/3ysqYVb) at CSUN in something that interests you.
-   Associated Students (https://bit.ly/3yuWjGT) offers recycling, and a Children's Center providing child care
-   Financial Aid & Scholarships (https://bit.ly/3sYFzqr) offers aid for applications
-   University Library https://bit.ly/3yuIEQ9) for many additional academic resources
-   Veterans Resource Center (https://bit.ly/38qYtg7) assists CSUN students as they transition from military service to academic success.

Title 5, California Code of Regulations,ยง 41301. Standards for Student Conduct -- (a) Campus Community Values: The university is committed to maintaining a safe and healthy living and learning environment for students, faculty, and staff. Each member of the campus community should choose behaviors that contribute toward this end. Students are expected to be good citizens and to engage in responsible behaviors that reflect well upon their university, to be civil to one another and to others in the campus community, and contribute positively to student and university life.

CSUN with A HEART If you are facing challenges related to food insecurity, housing precarity/homelessness, mental health, access to technology, eldercare/childcare, or healthcare, you can find guidance, help, and resources from CSUN with A HEART (https://www.csun.edu/heart).

## Course Sequence

{{< include sequence.qmd >}}

## References

::: {#refs}
:::
